### Register New USer
POST http://localhost:8080/
Content-Type: application/json
X-API-KEY: SECRET_API_KEY
Authorization: Bearer sasakdnaa.dsanspidaos.oinaonsdnoasdnisdpaodsds

{
  "username" : "johndoe",
  "email" : "johndoe",
  "password" : "johndoe123"
}

### UPLOAD PHOTO
POST http://localhost:8080/upload
Content-Type: image/jpeg

home/dds
